apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Les ressources de base
resources:
  - fastapi/fastapi-deployment.yaml
  - fastapi/fastapi-service.yaml
  - mysql/mysql-pv-pvc.yaml
  - mysql/mysql-secret.yaml
  - mysql/mysql-service.yaml
  - mysql/mysql-statefulset.yaml
  - mysql/namespace-standard.yaml
  - phpmyadmin/phpmyadmin-deployment.yaml
  - phpmyadmin/phpmyadmin-secret.yaml
  - phpmyadmin/phpmyadmin-service.yaml

