apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fastapi.secret.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.fastapi.secret.mysqlRootPassword }}
