apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fastapi.ingress.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.fastapi.clusterIssuer.name }}
spec:
  ingressClassName: traefik
  tls:
    - secretName: {{ .Values.fastapi.ingress.secretName }}
      hosts:
        - {{ .Values.fastapi.ingress.host }}
  rules:
    - host: {{ .Values.fastapi.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.fastapi.service.name }}
                port:
                  number: {{ .Values.fastapi.service.port }}

