apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.fastapi.hpa.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fastapi.deployment.name }}
  minReplicas: {{ .Values.fastapi.hpa.minReplicas }}
  maxReplicas: {{ .Values.fastapi.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.fastapi.hpa.targetCPUUtilizationPercentage }}

