
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.rootPasswordSecret }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlPasswordRoot }}

