apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: mysql-username
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: mysql-password
